'use client';

import React, { useState } from 'react';
import { CreateBlogPostDto, BlogPost, UpdateBlogPostDto } from '../types';
import { Button } from '@/components/ui/button';

interface BlogPostFormProps {
  initialData?: BlogPost;
  onSubmit: (data: CreateBlogPostDto | UpdateBlogPostDto) => Promise<void>;
  isLoading?: boolean;
}

export function BlogPostForm({ initialData, onSubmit, isLoading }: BlogPostFormProps) {
  const [formData, setFormData] = useState<CreateBlogPostDto>({
    title: initialData?.title || '',
    slug: initialData?.slug || '',
    content: initialData?.content || '',
    published: initialData?.published ?? false,
  });

  const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(!initialData);

  const generateSlug = (title: string) => {
    return title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)+/g, '');
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value, type } = e.target;
    const checked = (e.target as HTMLInputElement).checked;

    setFormData((prev) => {
      const newData = {
        ...prev,
        [name]: type === 'checkbox' ? checked : value,
      };

      if (name === 'title' && isSlugAutoGenerated && !initialData) {
        newData.slug = generateSlug(value);
      }

      return newData;
    });

    if (name === 'slug') {
      setIsSlugAutoGenerated(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    await onSubmit(formData);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6 max-w-2xl bg-card p-6 border rounded-xl shadow-sm">
      <div className="space-y-2">
        <label htmlFor="title" className="text-sm font-semibold">Title</label>
        <input
          id="title"
          name="title"
          value={formData.title}
          onChange={handleChange}
          required
          placeholder="Post Title"
          className="w-full px-3 py-2 bg-background border rounded-md focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all"
        />
      </div>
      <div className="space-y-2">
        <label htmlFor="slug" className="text-sm font-semibold">Slug</label>
        <input
          id="slug"
          name="slug"
          value={formData.slug}
          onChange={handleChange}
          required
          placeholder="post-title"
          className="w-full px-3 py-2 bg-background border rounded-md focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all"
        />
      </div>
      <div className="space-y-2">
        <label htmlFor="content" className="text-sm font-semibold">Content (Markdown)</label>
        <textarea
          id="content"
          name="content"
          value={formData.content}
          onChange={handleChange}
          required
          rows={15}
          placeholder="Write your article content in Markdown..."
          className="w-full px-3 py-2 bg-background border rounded-md focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all resize-y"
        />
      </div>
      <div className="flex items-center gap-2">
        <input
          id="published"
          name="published"
          type="checkbox"
          checked={formData.published}
          onChange={handleChange}
          className="w-4 h-4 rounded border-gray-300 text-primary focus:ring-primary"
        />
        <label htmlFor="published" className="text-sm font-semibold cursor-pointer">Published</label>
      </div>
      <div className="flex justify-end gap-3 pt-4">
        <Button
          type="button"
          variant="outline"
          onClick={() => window.history.back()}
          disabled={isLoading}
        >
          Cancel
        </Button>
        <Button
          type="submit"
          disabled={isLoading}
        >
          {isLoading ? 'Saving...' : initialData ? 'Update Post' : 'Create Post'}
        </Button>
      </div>
    </form>
  );
}
